assets:
  npmrc: objectionary/secrets#npmrc
install: |
  sudo apt-get -y update
  sudo npm install --no-color --global grunt
  npm install --no-color
  pdd -f /dev/null -v
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/^\"version\": \"0.0.0\"/\"version\": \"${tag}\"/" package.json
    grunt --no-color
    git commit -am "${tag}"
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
merge:
  script: |-
    grunt
deploy:
  script: |-
    echo "There is nothing to deploy"
    exit -1
