docker:
  image: yegor256/rultor-image:1.9.0
assets:
  npmrc: yegor256/objectionary-secrets#npmrc
install: |
  pip install git+https://chromium.googlesource.com/external/gyp
  npm install --no-color
  sudo npm install --no-color --global grunt-cli
  npm uninstall --no-color grunt-cli
  npm install --no-color mocha
  pdd -f /dev/null -v
release:
  script: |
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    sed -i -e "s/\"version\": \"0.0.0\"/\"version\": \"${tag}\"/" package.json
    sed -i -e "s/0.0.0/${tag}/" src/version.js
    grunt --no-color
    git commit -am "set version to ${tag}"
    chmod 600 ../npmrc
    npm publish --no-color --userconfig=../npmrc
merge:
  script: |-
    grunt --no-color
