name: itest
on:
  push:
  pull_request:
concurrency:
  group: itest-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java: [11, 18]
        node: [12, 16]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - run: npm install
    - run: cd itest && node ../src/eoc.js --parser=0.36.0 --home-tag=afc6c10c54e28efe01f2352d699c137c3cb0a68d --batch dataize program
    - run: cd itest && node ../src/eoc.js --parser=0.36.0 --home-tag=afc6c10c54e28efe01f2352d699c137c3cb0a68d --alone --batch dataize program
    - run: cd itest && node ../src/eoc.js clean
    - run: cd itest && node ../src/eoc.js --parser=0.36.0 --home-tag=afc6c10c54e28efe01f2352d699c137c3cb0a68d --batch test
