name: itest
on:
  push:
  pull_request:
concurrency:
  group: itest-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java: [11, 18]
        node: [12, 16]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: ${{ matrix.java }}
    - run: npm install
    - run: cd itest && node ../src/eoc.js dataize program
    - run: cd itest && node ../src/eoc.js test
